### ISSUE TITLE
Move to signed images

### ISSUE THREAD

**Issue by gerblesh** [ublue-os/startingpoint#113]
Recently main just made the move to signed images, it would be ideal if the move was replicated in startingpoint. Here's what needs to be done:
- move the public key to `/usr/etc/pki/containers`
- include the proper parameters in the policy file

**Comment by gerblesh** [comment]
solved with https://github.com/ublue-os/startingpoint/pull/116

**Comment by xynydev** [comment]
Great work! I'm not really up-to-date on what this entails, but the PR still encourages some README updates and testing. If somebody could point me in the right direction for this?

**Comment by xynydev** [comment]
Should we recommend rebasing to `ostree-image-signed:docker://ghcr.io/...`?

Edit; Nevermind, I see the new README now.
