### ISSUE TITLE
Image signing fails when repository contains capital letters.

### ISSUE THREAD

**Issue by TRS-SoD** [ublue-os/startingpoint#118]
GitHub action fails on the 'Sign container image' step when the repository contains capital letters.

This is due to the variable "env.IMAGE_NAME" being automatically lowercased by GitHub when pushing the image to the registry, but capitalized when attempting to pull the image to run cosign.

I have fixed it on my own repository in this commit:
https://github.com/TRS-SoD/Indomitable/commit/f2ab510e400e53cc0399b9af086df63079fb76a7

Using a similar method used for the username capitalization workaround.

**Comment by xynydev** [comment]
Good to know, this is probably an oversight. I'll implement this change now.
