### ISSUE TITLE
Building kmods or akmods won't work during build (action using azure kernel)

### ISSUE THREAD

**Issue by MiMillieuh** [ublue-os/startingpoint#125]
Hello, 

I've noticed an annoyance with a lot of packages like VirtualBox or some Guest Tools from paralells on someone's computer,

It's impossible to install them cause when you execute akmods or something that relate to uname it will take the kernel from azure (the one that github uses to build and image) and so it won't find the kernel module folder for that one.

Any suggestions ? or potential fix ? 

Thanks ! 

**exemple of issue :** 

```
Checking kmods exist for 5.15.0-1041-azure [  OK  ]
Files needed for building modules against kernel
5.15.0-1041-azure could not be found as the following
directories are missing:
/usr/src/kernels/5.15.0-1041-azure/
/lib/modules/5.15.0-1041-azure/build/Is the correct kernel-devel package installed? [FAILED]
```

**Comment by xynydev** [comment]
Hey, sorry for not responding earlier, I have missed this issue completely. I am not familiar with this issue, and I don't think it's some problem with this template. You might have better luck on the discussion forum https://github.com/orgs/ublue-os/discussions or the Discord https://discord.gg/WEu6BdFEtp.

Can you clarify how you are trying to install akmods?

**Comment by MiMillieuh** [comment]
> 

Well I've tried by installing a kmod with the recipe.yml (exemple installing virtualbox akmod from the repo) and I've tried to make a sh script that will execute akmod after all rpms are installed but it use the old kernel from debian azure

**Comment by xynydev** [comment]
Have you looked at the ublue akmods repo for example? https://github.com/ublue-os/akmods

The scripts in there run an akmods command like `akmods --force --kernels "${KERNEL}" --kmod wl`.

It's also possible to request the akmods you need to be built there so you could just pull them from there.

**Comment by MiMillieuh** [comment]
The variable kernel works but you need to build akmods afterwads and that's kinda inconvenient

**Comment by xynydev** [comment]
Closing this issue. Building custom kernel modules with custom kernels is not something currently supported officially. This should be discussed somewhere else, if desired.
