### ISSUE TITLE
Why default branch "template"

### ISSUE THREAD

**Issue by plata** [ublue-os/startingpoint#128]
I tried to `git merge upstream/main` until I realized that the default branch is called `template`. Why is this? I understand that this is a template repository but the default branch could (should?) still be `main`.

**Comment by xynydev** [comment]
The default branch used to be called main, but we restructured to a non-default configuration where only a non-template branch called `live` is published, which simplified the updating of forks/children. This was kind of a confusing change and would have caused a lot more people to just edit the `main` branch, which used to be the correct way, so `main` was renamed to `template`.

I don't think it'd be necessary, or good, to change it back now.

**Comment by plata** [comment]
I'm not so sure if forks even realized that the default branch was changed or just assumed that there was no update (at least that's what I did).

**Comment by xynydev** [comment]
I am currently crunching on a work project, but once that calms down I'll look at the ISO building stuff and make a stable release. After that it should be no more breaking changes until another release, and keep it to mostly fixes and docs updates.

Note that this branch change was not something I pushed in, you can get more in-depth reasoning from @Arcitec https://github.com/ublue-os/startingpoint/pull/76

**Comment by plata** [comment]
@Arcitec can you elaborate a bit more on the envisioned workflow?

- Is the user supposed to fork or not? My understanding from previous discussions is that `startingpoint`  should be a [template repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template) and the user should *not* fork it such that they can create multiple repositories from the same template.
- Why would the user want a copy of the `template` branch in my repository? I understand that it allows syncing via GitHub GUI but rebasing still must be done manually. This can be done directly on the upstream branch.
- Why is the `live` branch released (instead of `main`)? This only has the effect that the `main` branch is called `live` which is at best confusing.

**Comment by xynydev** [comment]
> Is the user supposed to fork or not? My understanding from previous discussions is that startingpoint should be a [template repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template) and the user should not fork it such that they can create multiple repositories from the same template.

Fork, if possible. This allows for easier updates from the Github UI. Templating is turned on for some people who prefer it, or easier creation of multiple repos. 

> Why would the user want a copy of the template branch in my repository? I understand that it allows syncing via GitHub GUI but rebasing still must be done manually. This can be done directly on the upstream branch.

I am not sure about this, for there is some big-brain git-related reason. What I think I understand is that you sync the changes from `upstream:template` to `origin:template`, then PR -rebase the new changes and your own. There's some technical reason to why that is superb to just doing merge commits, which is what I personally do because 1. It works 2. I'm lazy 3. I don't need to see all my custom changes in order, I like to see all the changes (including updating from updates with merges) in order.

**Comment by plata** [comment]
Ok, if the plan is to do everything via GitHub GUI, I get the point.

Personally, I also merge instead of rebase. Latest when you work with more than one committer, rebasing the main branch will blow up.

**Comment by plata** [comment]
> Ok, if the plan is to do everything via GitHub GUI, I get the point.

Actually, still no. You can just open a cross repo PR to do the rebase.

Like this:
- startingpoint branch is `main`
- fork
- change `main` in your fork
- create PR from `startingpoint:main` to `fork:main`

**Comment by xynydev** [comment]
Closing this issue for now. This is the branch structure we have and I don't really see a reason to change back.
