### ISSUE TITLE
recipe.yml with enabled 'dconf-update-service' fails to build (new modular system)

### ISSUE THREAD

**Issue by dperson** [ublue-os/startingpoint#148]
```
Pulling from bling: dconf-update-service

Failed to enable unit, unit dconf-update.services.service does not exist.
```

Looks like there was a typo, an extra `s` was left on the end of the service file name to enable.

**Comment by xynydev** [comment]
Or maybe the typo is the dot in `dconf-update.services`, I'll check this out today.

**Comment by lorduskordus** [comment]
@xynydev https://github.com/ublue-os/bling/pull/36

**Comment by lorduskordus** [comment]
This still doesn't work. Related issue in bling repo: https://github.com/ublue-os/bling/issues/34
