### ISSUE TITLE
Disabling automatic updates

### ISSUE THREAD

**Issue by tunix** [ublue-os/startingpoint#158]
I decided to do automatic updates manually for a while so disabled the bling part in recipe. I use silverblue-main as base image. Looks like silverblue-main includes ublue-os/config and the automatic updates come from there as well.

How can I disable automatic updates? I also can't do `systemctl disable rpm-ostreed-automatic.timer` -- it's simply re-enabled everytime I do it. I don't know how.. 🤔

**Comment by xynydev** [comment]
There's a FAQ item for this. https://universal-blue.org/faq/?h=updates#how-do-i-configure-automatic-updates

You can also use the `systemd` module to disable timers. https://universal-blue.org/tinker/modules/systemd/

**Comment by xynydev** [comment]
Closing this now due to the issue being answered and there being no follow-up.
