### ISSUE TITLE
Intended that ISO release has multiple ISOs?

### ISSUE THREAD

**Issue by plata** [ublue-os/startingpoint#179]
e.g. https://github.com/plata/ublue-surface/releases/tag/auto-iso

Should the old ISOs get cleaned up?

**Comment by xynydev** [comment]
I wasn't aware of this behaviour, so it's not intended. It'd be an extra few lines of code, but isn't it kind of beneficial that there's multiple ISO versions available and the repo maintainer can on their end delete the extra ones(?)

**Comment by plata** [comment]
I don't think it's beneficial. In the end, the real data is downloaded only during installation (netinstall). So the release will list a bunch of ISOs which all do the same thing. This is at best useless and at worst confusing for the users.

**Comment by xynydev** [comment]
Hmm, ok, I'll make sure to fix it once I get the time.
