### ISSUE TITLE
Can ISO installation use signed image directly?

### ISSUE THREAD

**Issue by plata** [ublue-os/startingpoint#180]
After a fresh ISO installation, `rpm-ostree status` shows `ostree-unverified-image`.

**Comment by xynydev** [comment]
I'm not sure. A very simple configuration of https://github.com/ublue-os/isogenerator is used to generate ISOs. IIRC it's not possible, and you need some program like https://github.com/ublue-os/ublue-update to automatically rebase to the signed version based on image-info.json.

**Comment by plata** [comment]
Should startingpoint include ublue-update by default then to achieve this?

**Comment by xynydev** [comment]
No, it's a choice the image mainter has to make for themselves. The bling module already has a quick and easy way to install ublue-update https://universal-blue.org/tinker/modules/bling/
