### ISSUE TITLE
rpm-ostree rebase with or witout sudo?

### ISSUE THREAD

**Issue by plata** [ublue-os/startingpoint#182]
E.g. https://universal-blue.org/CONTRIBUTING/#building-locally doesn't use sudo but the README of this repository and https://docs.fedoraproject.org/en-US/iot/rebasing/ does.

What's the correct way?

**Comment by xynydev** [comment]
Umm, I think both would get you the same result. If you're not in `wheel` you can't `sudo` either so I guess without sudo, since I think it works, is fine and a bit shorter.
