### ISSUE TITLE
Installing flatpak packages with user instead of system

### ISSUE THREAD

**Issue by tunix** [ublue-os/startingpoint#203]
Yafti is shown when a user first logs in to its desktop. The user then picks some packages and install them. However those packages seem to be installed as system packages. I think the default should be to install them as user packages and maybe give the user an option to install some or all of them system packages as well.

Is there a reason why we don't install these packages as user packages?

**Comment by xynydev** [comment]
There is no specific reason. I don't use yafti myself, and such don't maintain a featureful default configuration, unlike many custom image maintainers. I consider the custom flatpaks part in the yafti module to be a legacy shortcut and I don't want to add any more features to it. The default yafti configuration is not something that's thought-out, it was just copied from some early versions of bluefin.

If you think installing the flatpaks for the user would be a better default behaviour, you can make a PR for it. The yafti config file and the specific part is here: https://github.com/ublue-os/startingpoint/blob/9aa7bb27404d97e862eb6065096a23ad2b6ea7f7/config/files/usr/share/ublue-os/firstboot/yafti.yml#L52-L54

In the future I think it would be cool if someone started maintaining a featureful default yafti configuration in ublue-os/bling, which would be used by default here. This would also require documentation on how to override the default config.

**Comment by xynydev** [comment]
Closing this now. If you wish for a change, contribute to the yafti.yml in https://github.com/blue-build/modules
