### ISSUE TITLE
Update Containerfile & Recipe

### ISSUE THREAD

**Issue by xynydev** [ublue-os/startingpoint#232]
- Account for changes in bling
- Replace yafti with default-flatpaks

**Comment by fiftydinar** [comment]
Oh, I already made PR:
https://github.com/ublue-os/startingpoint/pull/233

I can replace default-flatpaks there or in another PR if prefered.

**Comment by xynydev** [comment]
Actually, maybe we should just remove the bling module from the default recipe entirely. And one PR is preferred, creates less separate commits to manually merge.

**Comment by fiftydinar** [comment]
> Actually, maybe we should just remove the bling module from the default recipe entirely. And one PR is preferred, creates less separate commits to manually merge.

I agree.

I will remove bling module & change yafti to default-flatpaks

**Comment by fiftydinar** [comment]
Updated the same PR with removal of bling & replacement of yafti with default-flatpaks.
