### ISSUE TITLE
bug?: Changes made under etc/ are not applied with rpm-ostree update

### ISSUE THREAD

**Issue by tepene** [ublue-os/startingpoint#28]
I'm not sure if it's a bug, a feature, or if it's just my lack of understanding. My custom image <https://github.com/tepene/ublue-bayou> is based on this startingpoint. I'm getting along quite well ;) but now I'm struggling with updates.

According to <https://github.com/coreos/rpm-ostree/blob/main/docs/container.md#installing-config-files>

>You can use any tooling you want to generate config files in /etc. When a booted system pulls an updated container images, the changes will also be applied.

But that's not what is happening. For Example: I modified the `etc/yafti.yml`, rebuilt the image, uploaded it to my local registry and ran `rpm-ostree update` on my test machine. The new update gets applied and i reboot with `systemctl reboot`.
After the reboot I check the content of the `/etc/yafti.yml` on my test machine and it still has the "old" content. Not the "new" as I would have expected.

Am I missing something crucial. Is `etc/` only applied during a fresh installation and not during updates, or is there a magic command which I am missing? Any help is greatly appreciated.

**Comment by EinoHR** [comment]
Answer on our Discord:

![Screenshot_20230418-143942_1](https://user-images.githubusercontent.com/60004820/232766098-329387e4-8989-4b05-963a-b26a16a6bf88.png)

Referenced article:

https://blog.verbum.org/2014/01/24/why-ostree-requires-usretc/

---

We should probably change the default Containerfile to copy files to /usr/etc, but I'll check from the others first.

**Comment by elgabo86** [comment]
I don't know if my problem is related to this one but when I add for example virt-manager in the build script, the "libvirt" group does not merge in /usr/lib/group whereas if I install virt-manager as a layer packages, the group appears in this file.

**Comment by EinoHR** [comment]
> virt-manager

I think this is a different issue, I don't think this issue is affects RPMs. I've installed virt-manager in my own image and it works, no libvirt groups or qemu users, but no issues either. Is this something you except to be there ootb?

**Comment by elgabo86** [comment]
> > virt-manager
> 
> I think this is a different issue, I don't think this issue is affects RPMs. I've installed virt-manager in my own image and it works, no libvirt groups or qemu users, but no issues either. Is this something you except to be there ootb?

Yes virt-manager works but only with root privileges.

Normally with layered packages, just copy the line containing the "libvirt" group from /usr/lib/group to /etc/group and add the user in this group to be able to use virt-manager without root, the users "gluster " "qemu" "saslauth" are created automatically in /etc/passwd. But when the packages are installed with the script, the "libvirt" group does not exist in /usr/lib/group and the "gluster" "qemu" "saslauth" users are not created.

**Comment by tepene** [comment]
> We should probably change the default Containerfile to copy files to /usr/etc, but I'll check from the others first.

Thanks! I just did some simple tests with the file `/etc/justifile` after I changed `COPY etc /etc` to `COPY etc /usr/etc` in my Containerfile.

## Test cases
### Install from scratch
After changing the Containerfile in my source, I rebased the new image on a freshly staged VM.

:heavy_check_mark: Files affected by `COPY etc /usr/etc` get copied to `/etc`. Everything fine.

### Add some lines to `/etc/justifile` in my source
Then I added some lines to the `/etc/justifile` in my source. Rebuilt the image and updated the VM

:heavy_check_mark: Changes from my source got applied to file on my VM. Everything fine.

### Removed some lines from `/etc/justifile`  in my source
Then I deleted some lines to the `/etc/justifile` in my source. Rebuilt the image and updated the VM

:heavy_check_mark:  Changes from my source got applied to file on my VM. Everything fine.

### Add some lines to `/etc/justifile`  on my VM and some lines to `/etc/justifile` in my source
Then I added some lines to `/etc/justifile` on my VM and I also changed some lines in `/etc/justifile`  on my source. Rebuilt the image and updated the VM.

:warning: This time, the file on the VM didn't get updated. Only the file under `/user/etc`.

The `ostree admin config-diff` shows exactly that.
```sh
$ sudo ostree admin config-diff | grep justfile
M    justfile
```
Is there a way to resolve the config-diff?

**Comment by EinoHR** [comment]
Thank's for the extensive testing @tepene !

> Is there a way to resolve the config-diff?

I'd assume the command just looks at the direct difference in the files in the case auto-merging is not possible. You'd probably do a manual merge then, deciding if the updates from the image are something you want to add to your own /etc/justfile

**Comment by tepene** [comment]
one possible solution I found is  `rsync -avh /usr/etc/ /etc/ --delete` which is noted here https://community.toradex.com/t/manually-reset-of-modified-etc-files-to-current-ostree-commit/15748/4

This might be useful if you want to "reset" your system back to the original state.

**Comment by EinoHR** [comment]
#43 merged, it's done.
