### ISSUE TITLE
feat: adding repos in recipe.yml?

### ISSUE THREAD

**Issue by EinoHR** [ublue-os/startingpoint#35]
This could be a useful feature since rpm-ostree currently has no command for this.
How it would work is you copy a download link for the repo file (could even be your own gist or a file in the repo or smth) and it's downloaded into `/etc/yum.repos.d/` [(or perhaps /usr/etc/?)](https://github.com/ublue-os/startingpoint/issues/28#issuecomment-1512933644) in `build.sh`.

The procedure for enabling a COPR repo then would be going to the repo's page (ex. https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/) and copying the correct link from the `Repo Download` section by right-clicking on the button.

**Comment by federdaemn** [comment]
I would like it but I think that we then should also have a way to add gpg keys to the keyring.

**Comment by EinoHR** [comment]
> I would like it but I think that we then should also have a way to add gpg keys to the keyring.

How would we do that and what would be the benefit? I haven't ever needed to do that, but adding custom repos is probably commonplace.
