### ISSUE TITLE
fix: moving recipe back to a directory available on the host

### ISSUE THREAD

**Issue by EinoHR** [ublue-os/startingpoint#36]
Currently the `just setup-flatpaks` command is broken (because of https://github.com/ublue-os/startingpoint/commit/e9c31aba83b4a158c47c0306e9fecd9d00c4ffa9). In light of this, the recipe should probably be moved to some folder accessible on the host computer.

That folder probably shouldn't be `/etc/`, though, as that implies that it's a config file that can be edited, when it should only be changed inside the git repository.

**Comment by federdaemn** [comment]
I like the concept of /.well-known/ so maybe we should copy it to /well-known/ (without the dot). There it would be accesibke for everyone.
Or is there a standart directory for package files? Like we use the package name ublue-os.

**Comment by EinoHR** [comment]
Isn't well-known related to webserves and SSL? I'd prefer a standard Linux root directory. I'm thinking just `/usr/` would do. `/usr/ublue-recipe.yml`.

**Comment by federdaemn** [comment]
Or /var/ because it's a file that can change.
I think that /usr/ is bad because I read that it is also for programs.

**Comment by EinoHR** [comment]
> Or /var/ because it's a file that can change. I think that /usr/ is bad because I read that it is also for programs.

Var is not something we can write to, and the file shouldn't be changed by the user on the computer (does nothing), only in git.

`/usr/` I think is our only choice then, but it doesn't normally contain config files. Maybe `/usr/etc/` could just do, which is basically the same as putting it in `/etc/`. Then just add a warning for users to not change the file on their system...

Not just putting it to `/etc/` straight away was probably overthinking.
