### ISSUE TITLE
feat: add a just setup command for setting up nix

### ISSUE THREAD

**Issue by dnkmmr69420** [ublue-os/startingpoint#39]
title

**Comment by federdaemn** [comment]
Yes, please. With an official, easy to read setup script.

**Comment by EinoHR** [comment]
> just should also be able to update nix and also fleek if installed

We had this issue on base I believe. My answer; someone who uses Nix should PR it.

**Comment by dnkmmr69420** [comment]
What do I even PR?

**Comment by EinoHR** [comment]
> What do I even PR?

What do you mean by that? This repo, the justfile?, any addition you want, really? I thought you wanted `just update` to update Nix.

**Comment by federdaemn** [comment]
> 
> We had this issue on base I believe. My answer; someone who uses Nix should PR it.

Do you know the issue on base? I could work on this, likely wednesday.

**Comment by EinoHR** [comment]
> Do you know the issue on base? I could work on this, likely wednesday.

Apparently it was @dnkmmr69420 that time too https://github.com/ublue-os/base/issues/82.

**Comment by federdaemn** [comment]
Thanks. I will look at that.

**Comment by EinoHR** [comment]
@dnkmmr69420 @federdaemn if yall want `just update` to update nix stuff too, please either pr it in or reply to PR #48 with the script (needs to check if nix is installed) and I'll put you as co-author

**Comment by federdaemn** [comment]
I was working on this (https://github.com/federdaemn/2.1-ublue-startingpoint/blob/main/etc/justfile) justfile until now and it includes a command to install home-manager and update both as well too.

I don't know if we should use yours and I will discard my setup-nix command or if we should use mine.

**Comment by EinoHR** [comment]
> I don't know if we should use yours and I will discard my setup-nix command or if we should use mine.

My nix setup command is the same as bluefin's, so I think we should use that.

**Comment by EinoHR** [comment]
@federdaemn How does this look? https://github.com/ublue-os/startingpoint/pull/48/commits/01acbf75251bbfaddf4bb8acabef0144c18e286a

**Comment by federdaemn** [comment]
Looks great to me.
If that's merged I will work on a command to install & update home-manager and fleek. That shouldn't take to long.

**Comment by federdaemn** [comment]
I your pull request is merged I can start my own for home-manager tomorrow evening.
