### ISSUE TITLE
docs: Remove/Relax "Fedora Silverblue" in README description

### ISSUE THREAD

**Issue by plata** [ublue-os/startingpoint#56]
> This is a starting point Fedora Silverblue image designed to be customized to whatever you want

As the recipe is based on silverblue-main, this is correct.

Still, it might not be the  best wording for the description section of the startingpoint repository. For example, a user might wonder if it doesn't work for Kinoite (I know that this is clarified later in "Customization").

I'm still not 100% clear on what ublue OS (and thus the startingpoint) really **is** or **shall be**, so I find it hard to find a better wording myself. I currently see these options:
1. Fedora ostree + extensions
2. OCI defined OS which just happens to be Fedora but could be anything else
3. A framework/toolset to define/maintain an OCI defined OS

I see that the original topic for this issue led to very fundamental considerations which probably shouldn't even be in this repo, so sorry for that. Nevertheless, I hope my point became clear.

EDIT: Just saw https://github.com/orgs/ublue-os/discussions/125.

**Comment by EinoHR** [comment]
Hope this cleaned things up
