### ISSUE TITLE
Use dependabot?

### ISSUE THREAD

**Issue by plata** [ublue-os/startingpoint#57]
Got this after forking: https://github.com/plata/ublue-surface/pull/1

**Comment by EinoHR** [comment]
I think we're using dependabot, yeah, https://github.com/ublue-os/startingpoint/blob/main/.github/dependabot.yml.
Most of the time you can just go ahead and merge the PRs it generates, or close them and wait until this repo updates (whenever dependabot alerts us to)

**Comment by plata** [comment]
Ah I see, the schedule is weekly. So that's likely the reason why I already got the PR.
