### ISSUE TITLE
Nix Flakes or normal Nix?

### ISSUE THREAD

**Issue by federdaemn** [ublue-os/startingpoint#59]
Shall we use flakes (and nix profile) or not (and nix-env) in the justfile?

I'm for flakes because they are easier for the developers and is uses flake references to find packages so a package with the same name works well (https://www.reddit.com/r/NixOS/comments/10s2298/comment/j6zdtfq/). I also think that then it's easier to use fleek.
Any other opinions because if we're using flakes I will need to change the justfile.

@dnkmmr69420

**Comment by federdaemn** [comment]
I will close this and not open a pr because nobody answered and users should decide on themselve.

**Comment by EinoHR** [comment]
> I will close this and not open a pr because nobody answered and users should decide on themselve.

Good choice then. We'll revisit if somebody requests this feature (`just update` to update nix packages) again.
