### ISSUE TITLE
Add example for kernel replacement

### ISSUE THREAD

**Issue by plata** [ublue-os/startingpoint#60]
I'm trying to use the [linux-surface](https://github.com/linux-surface/linux-surface) kernel.

In a VM, the following works:
```
sudo wget -O /etc/yum.repos.d/linux-surface.repo \
    https://pkg.surfacelinux.com/fedora/linux-surface.repo
wget https://github.com/linux-surface/linux-surface/releases/download/silverblue-20201215-1/kernel-20201215-1.x86_64.rpm
rpm-ostree override replace ./*.rpm
```
see https://github.com/linux-surface/linux-surface/issues/1128

However, in the `Containerfile`:
```
RUN wget -O /etc/yum.repos.d/linux-surface.repo https://pkg.surfacelinux.com/fedora/linux-surface.repo && \
    wget https://github.com/linux-surface/linux-surface/releases/download/silverblue-20201215-1/kernel-20201215-1.x86_64.rpm  && \
    rpm-ostree override replace ./*.rpm && \
    rpm-ostree install surface-secureboot
```
This shows an error when generating initramfs during the build. Interestingly, the build still succeeds but after rebasing to the image, it boots with kernel panic.
![kernel panic](https://user-images.githubusercontent.com/3973260/235445029-37a6a412-7ccc-46d7-8e97-2ce9a2c5561e.png)

The error:
```
dracut: No '/dev/log' or 'logger' included for syslog logging
dracut: Executing: /usr/libexec/rpm-ostree/wrapped/dracut --no-hostonly --kver 6.2.13-1.surface.fc38.x86_64 --reproducible -v --add ostree -f /tmp/.tmpOqYwdG/initramfs.img
dracut: /lib/modules/6.2.13-1.surface.fc38.x86_64//modules.dep is missing. Did you run depmod?
error: rpm-ostree kernel-install wrapper: Running dracut: Failed to generate initramfs (via dracut) for for kernel: 6.2.13-1.surface.fc38.x86_64: ExitStatus(unix_wait_status(256))
```

I tried to follow https://github.com/coreos/layering-examples/blob/main/replace-kernel/Containerfile but it gives the same issue.
```
RUN rpm-ostree override replace https://github.com/linux-surface/linux-surface/releases/download/fedora-38-6.2.13-1/kernel-surface-6.2.13-1.fc38.x86_64.rpm \
                                https://github.com/linux-surface/linux-surface/releases/download/fedora-38-6.2.13-1/kernel-surface-devel-6.2.13-1.fc38.x86_64.rpm
```

I don't think that this is specific to that kernel, so having some guideline on how to replace the kernel would be greatly appreciated.

**Comment by plata** [comment]
When following the surface-linux guide, I get
```
error: Could not depsolve transaction; 1 problem detected:
 Problem: package kernel-devel-matched-6.2.15-300.fc38.x86_64 from @System requires kernel-core = 6.2.15-300.fc38, but none of the providers can be installed
  - conflicting requests
```

This doesn't happen with base `quay.io/fedora-ostree-desktops/kinoite`. What's the difference in ublue?

**Comment by xynydev** [comment]
uBlue adds kernel modules, could that be it? I recommend also asking on Discord with the others.

**Comment by KE0VVT** [comment]
I [used JosSamLoh's script](https://github.com/KE0VVT/panama/commit/d69728474508cbe8e055bee40ae3abc8cb0609ab) to replace the kernel, but it did not work.

**Comment by plata** [comment]
That looks pretty similar to what I tried without success as well.

**Comment by xynydev** [comment]
Closing this issue now. Future efforts towards documentation for kernel replacement in images based on uBlue should be done under ublue-os/website, specifically added under an "Advanced" section in the Tinkerer's guide. In the meanwhile, discuss here https://github.com/orgs/ublue-os/discussions/169

**Comment by plata** [comment]
See https://github.com/ublue-os/surface/blob/04f10b17d13503dab2b737bebdfe63f5c6a84788/Containerfile#L19.

**Comment by plata** [comment]
I've copied the commands but it still doesn't work. Could it be that startingpoint behaves differently?

**Comment by xynydev** [comment]
> I've copied the commands but it still doesn't work. Could it be that startingpoint behaves differently?

Are you basing on an image with kmods?

**Comment by plata** [comment]
Not quite sure: I based on ghcr.io/ublue-os/kinoite-main:38 should that have kmods?

**Comment by xynydev** [comment]
Yeah, I think that should be fine. There's no reason this shouldn't work AFAIK, so it just depends on diagnosing what kinda errors you're getting.

**Comment by plata** [comment]
After looking at the [surface workflow](https://github.com/ublue-os/surface/blob/main/.github/workflows/build.yml) and the [changes to kmods](https://github.com/ublue-os/main/issues/369), my understanding is that I must use `*-nokmods` for < 39 and `*-main` for >= 39.
