### ISSUE TITLE
`Operation not permitted` when cleaning deployments

### ISSUE THREAD

**Issue by noahdotpy** [ublue-os/startingpoint#75]
```
$ rpm-ostree upgrade   
note: automatic updates (stage) are enabled
Pulling manifest: ostree-unverified-image:docker://ghcr.io/noahdotpy/myublue-gnome:latest
Staging deployment... done
error: Cleaning deployments: Removing ostree/deploy/fedora/deploy/1f9d6a5f0adc8a7a3a74bbc0d8d840714e283b391bfdbb90f3040512c1aa4f7d.0: unlinkat(resolv.conf): Operation not permitted
```

Here you can see that I am attempting to do a system upgrade on my uBlue image however it says it's unable to clean deployments! Yesterday I have also noticed that [at startup] there is a notification warning me that there is 0 bytes left available in the `/boot` partition. How can I cleanup `/boot/ostree` as that is the giant folder in there (taking up 940 MiB)
i am wondering how to fix the `Operation not permitted` message and also to cleanup `/boot/ostree`
when i do

```
$ rpm-ostree cleanup -b -r -p 
error: cleanup: GDBus.Error:org.projectatomic.rpmostreed.Error.Failed: syscore cleanup: Cleaning deployments: Removing ostree/deploy/fedora/deploy/1f9d6a5f0adc8a7a3a74bbc0d8d840714e283b391bfdbb90f3040512c1aa4f7d.0: unlinkat(resolv.conf): Operation not permitted
```
you can see that i cannot cleanup with that either
neither does it work with sudo ostree admin cleanup as it displays the same error as rpm-ostree upgrade

**Comment by EinoHR** [comment]
Not sure how I can help you, but this probably isn't uBlue specific.
I found [two](https://github.com/coreos/rpm-ostree/issues/3053) [issues](https://github.com/ostreedev/ostree/issues/2478) with similar errors in upstream repos, but I have no idea if they're related at all.

I wonder if your OS disk is too small for something you've tried to install, hmm. I don't know if that can be the issue.

**Comment by castrojo** [comment]
>  ostree-unverified-image

This should be ostree-unverified-registry:

    rpm-ostree rebase ostree-unverified-registry:ghcr.io/noahdotpy/myublue-gnome:latest

starts to work without an error for me

**Comment by EinoHR** [comment]
Good catch!

**Comment by noahdotpy** [comment]
I think the reason for all of this was because I made `/etc/resolv.conf` immutable with `sudo chattr +i /etc/resolv.conf`
