### ISSUE TITLE
add warning that ublue-os/startingpoint image won't be updated anymore

### ISSUE THREAD

**Issue by f7zorn** [ublue-os/startingpoint#80]
I think this will confuse newcomers because the startingpoint image does not get pushed after PR #76.

**Comment by xynydev** [comment]
ublue-os/startingpoint is not meant to be rebased on and that's never been recommended by any part of documentation. If you've made your own fork, when merging / rebasing on new changes, you should see the additions in the documentation telling you to create a branch called `live`. If you're a newcomer, and read the documentation, it should be pretty clear that the image not being updated is not a problem.

If there's any confusion you feel is not adequately covered by these, please comment below on where you think a notice should be added.

**Comment by f7zorn** [comment]
Then maybe the old package should be deleted?

**Comment by xynydev** [comment]
> Then maybe the old package should be deleted?

Sure! I can't do that tho (@castrojo) It also seems that my personal image got built too when I accidentally pushed my own repo's live branch into this repo (smh) https://github.com/ublue-os/startingpoint/pkgs/container/linuxyz, so that should be deleted too.

**Comment by castrojo** [comment]
Done!

**Comment by f7zorn** [comment]
Looks good to me.
