### ISSUE TITLE
Images created aren't versioned in rpm-ostree status

### ISSUE THREAD

**Issue by marinmo** [ublue-os/startingpoint#86]
Hello,

I filed this in https://github.com/EinoHR/create-ublue-image/issues/18 at first but was referred here.

When using standard ublue images, output of rpm-ostree is as such;

```
  ostree-unverified-registry:ghcr.io/ublue-os/silverblue-main:38
                   Digest: sha256:9f2d4a03d1d09612d5c8b3f6a7d6be40dc3be6cabb85d96a13b3eef6f9bead52
                  Version: 38.20230513.0 (2023-05-13T16:43:33Z)
      RemovedBasePackages: package_1
          LayeredPackages: package_2
```

When using an image created using startingpoint (by using the aforementioned tool), output is;

```
  ostree-unverified-registry:ghcr.io/marinmo/satellite-ublue:latest
                   Digest: sha256:f97de18e51c853e5f6b6a72555890af8fb09720cf822b9b4fcaf9908614f8532
                Timestamp: 2023-05-14T21:21:11Z
```

I'm wondering why the version (I realise this is just a concatenation of the fedora version+date+id) isn't displayed in the images created by my workflow? This seems like a slight bug to me, as comparing timestamps is less readable than the Versioning.

Thanks in advance for your consideration!

**Comment by xynydev** [comment]
I confirm this issue but think it is low priority.

This is the section where the version is ingested https://github.com/ublue-os/startingpoint/blob/d5a35ca31bf3e9820d4cb9704eadf42e8e569bea/.github/workflows/build.yml#L104

And this is where it is set https://github.com/ublue-os/startingpoint/blob/d5a35ca31bf3e9820d4cb9704eadf42e8e569bea/.github/workflows/build.yml#L119C1-L119C1

Equivalent file and lines in ublue-os/main https://github.com/ublue-os/main/blob/36711fa635afba4dcb2be667fadc96a8d9feeb48/.github/workflows/build.yml#L92

Our problem here is: using (which doesn't exist) `${{ env.SOURCE_IMAGE }}:${{ matrix.major_version }}` as image url the version tag.

An easy fix is replacing it with `${{ env.BASE_IMAGE_URL }}:${{ env.FEDORA_MAJOR_VERSION }}`.
