### ISSUE TITLE
Option to remove nonfree repos

### ISSUE THREAD

**Issue by KE0VVT** [ublue-os/startingpoint#88]
I'm trying to make a version of Fedora with a blob-free kernel and no proprietary software in the software repositories. I notice a lot of nonfree software like Steam is suggested by default, and RPMFusion nonfree is added by default. How do I remove RPMFusion-nonfree?

**Comment by xynydev** [comment]
You can just remove the .repo files manually from `/etc/yum.repos.d/` (in a script for example). Doesn't the vanilla kernel have proprietary blobs? You should attend the conversation on https://github.com/ublue-os/startingpoint/issues/60 for kernel replacement. I'm not entirely knowledgeable on how it is possible.

**Comment by KE0VVT** [comment]
I removed it. Thanks!
