### ISSUE TITLE
We need a proper way of handling custom repo files

### ISSUE THREAD

**Issue by tunix** [ublue-os/startingpoint#97]
Sometimes we may want to add hardcoded repo files instead of downloading them on the fly as we do for COPR repo's. [1Password is an example to this scenario](https://support.1password.com/install-linux/#centos-fedora-or-red-hat-enterprise-linux).

Placing the repo file inside /usr directory is OK when one wants to install it after the initial setup process. But for installing it during initial setup, we have to copy the repo files to /etc.

It'd be nice if we have an official and nice way of including such files.

**Comment by f7zorn** [comment]
I had the same problem because I want VSCode in my image.

I  have created a new repository, then I have uploaded the .repo file and I've just used the raw url as .repo link. This works great!

**Comment by federdaemn** [comment]
I had the same problem because I want VSCode in my image.

I  have created a new repository, then I have uploaded the .repo file and I've just used the raw url as .repo link. This works great!

**Comment by xynydev** [comment]
> I have created a new repository, then I have uploaded the .repo file and I've just used the raw url as .repo link. This works great!

You can also upload the file in the same repo as the image.   
   
   

RE:
![image](https://github.com/ublue-os/startingpoint/assets/60004820/9d1a43a9-79aa-4616-9bfc-9752c849c735)
You posted the same comment twice.

**Comment by xynydev** [comment]
Some solutions I'm thinking of rn:

* Document adding .repo files in the repo and then putting the link to the raw file in the recipe
* Merge `/usr/etc/yum.repos.d/` into `/etc/yum.repos.d/` before installing RPMs in the image
* Document adding a line in the `Containerfile` to copy the .repo files to `/etc/yum.repos.d/` directly

**Comment by f7zorn** [comment]
> You posted the same comment twice.

That was not intended.
